server:
  port: 8080

spring:
  application:
    name: authentication
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/auth
    username: sa
    password:
  h2.console.path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


oauth:
  kakao:
    client-id: a06411c55dacfcfc075606f7c2ed0490
    secret-id: Cimyx8SZHThjalZAbtEgVITsaFoKGf8b
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
    redirect_uri: http://localhost:12301/auth/login/kakao



