server:
  port: 12301
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationHeader
  jwt:
    secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

